Repository nextcloud/assistant, pull requests merged in 2025-06, with the labels that each got.

#249 ci: update node.yml workflow from template
  .github/workflows/node.yml
Labels: dependencies

#262 Fix input preservation
  src/components/AssistantTextProcessingForm.vue
Labels: bug, 3. to review

#288 Use outline icons where it makes sense
  src/components/ChattyLLM/ChattyLLMInputForm.vue
  src/components/ChattyLLM/Message.vue
  src/components/ChattyLLM/MessageActions.vue
  src/components/ContextChat/ContextChatInputForm.vue
  src/components/TaskListItem.vue
  src/components/Translate/TranslateForm.vue
  src/components/fields/AudioRecorderWrapper.vue
  src/components/fields/ChooseInputFileButton.vue
  src/components/fields/ListOfMediaField.vue
  src/components/fields/ListOfTextsField.vue
  src/components/fields/MediaField.vue
  src/components/fields/TextInput.vue
  src/components/fields/UploadInputFileButton.vue
  src/components/icons/CopyIcon.vue
  src/components/icons/DeleteIcon.vue
Labels: enhancement, 3. to review
